version: 0.2
phases:
  pre_build:
    commands:
      - echo "REACT_APP_API_URL=${REACT_APP_API_URL}" > .env
  build:
    commands:
      - npm install
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'